rm(list = ls())
load("C:/Users/suman/Desktop/List_of_tallest_dams_in_the_United_States.xlxs")
getwd()
setwd("C:/Users/suman/Desktop")
read.csv("List_of_tallest_dams_in_the_United_States.csv")
Dams<-read.csv("List_of_tallest_dams_in_the_United_States.csv")
Dams
View(Dams)
summary(Dams)
summary(Dams$Height)
max(Dams$Height.in.m)
min(Dams$Height.in.m)
mean(Dams$Height.in.m)
median(Dams$Height.in.m)
mode(Dams$Height.in.m)
sd(Dams$Height.in.m)
library(moments)
skewness(Dams$Height.in.m)
Dams[which.max(Dams$Height.in.m),]
library(ggplot2)
qplot(Dams$Height.in.m)
attach(Dams)
plot( Height.in.m, main = "Year vs Height",xlab="Built ", ylab="Height ", pch=2)
